MYSQL_CONFIG:
  name: 'nestjscli'
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'Root18720706348'
  database: 'nestjscli'
  entities: 'mysql'
  timezone: 'local'
  synchronize: true
